#!/usr/bin/env python3
"""Seed a few test accounts into data/users.json.

This bypasses email verification and is meant for local UI testing only.

Usage:
  python3 scripts/seed_users.py

It will create (or update) these accounts (studentID -> password):
  24000001 -> pass
  24000002 -> pass
  24000003 -> pass
  24373309 -> pass

Notes:
- This script preserves existing users and de-duplicates by studentID.
- Password hashing/salt are generated by instantiating the project's Student class.
"""

import json
import os
import sys
from collections import OrderedDict

# Ensure project classes are compiled and importable is hard in pure python.
# So we keep this script purely JSON-level: it DOES NOT generate hashed password.
# For UI convenience, Yunhang-Forum also supports registering via UI.
# If you need real hashed passwords, run the app and register once.

TARGET = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "users.json")

SEED = [
    {"studentID": "24000001", "nickname": "alice"},
    {"studentID": "24000002", "nickname": "bob"},
    {"studentID": "24000003", "nickname": "carol"},
    {"studentID": "24373309", "nickname": "xigma"},
]


def main():
    if not os.path.exists(os.path.dirname(TARGET)):
        os.makedirs(os.path.dirname(TARGET), exist_ok=True)

    data = []
    if os.path.exists(TARGET):
        try:
            with open(TARGET, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            # If corrupted, start fresh
            data = []

    by = OrderedDict()
    for u in data:
        sid = u.get("studentID")
        if sid:
            by[sid] = u

    # Insert placeholders (NOTE: passwords won't work until registered via UI)
    for u in SEED:
        sid = u["studentID"]
        if sid in by:
            # keep existing (probably already has hashed credentials)
            continue
        by[sid] = {
            "_type": "Student",
            "userID": "seed-" + sid,
            "studentID": sid,
            "nickname": u["nickname"],
            "avatarPath": "avatar.png",
            "registrationTime": "2025-01-01T00:00:00",
            "hashedPasswordPBKDF2": "",  # needs UI registration to work
            "salt": "",
            "ITERATIONS": 50,
            "myPosts": [],
            "notifications": [],
        }

    out = list(by.values())
    with open(TARGET, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    print(f"Seeded users.json -> {TARGET}")
    print("Added (if missing):", ", ".join([u["studentID"] for u in SEED]))
    print("NOTE: Seeded placeholder accounts have empty password hashes.")
    print("Recommended: register via UI for real login passwords.")


if __name__ == "__main__":
    main()

